import 'package:drift/drift.dart';

class LocalMessages extends Table {
  /// Local auto ID used even before the server creates a real message ID.
  IntColumn get localId => integer().autoIncrement()();

  /// Server message ID from Laravel. Nullable while message is pending.
  IntColumn get serverId => integer().nullable().unique()();

  IntColumn get conversationId => integer()();

  IntColumn get senderId => integer()();

  TextColumn get body => text()();

  /// For v1 this will be "text".
  TextColumn get type => text().withDefault(const Constant('text'))();

  TextColumn get payloadJson => text().nullable()();

  /// pending, sent, delivered, read, failed
  TextColumn get status => text().withDefault(const Constant('pending'))();

  /// UUID generated by Flutter before sending.
  TextColumn get clientMessageId => text().nullable().unique()();

  /// Server-side ordering inside conversation.
  /// Nullable while message is still pending locally.
  IntColumn get serverSequence => integer().nullable()();

  /// Local created time. Used temporarily for pending display.
  DateTimeColumn get createdAt => dateTime()();

  /// Server accepted the message.
  DateTimeColumn get serverReceivedAt => dateTime().nullable()();

  DateTimeColumn get deliveredAt => dateTime().nullable()();

  DateTimeColumn get readAt => dateTime().nullable()();

  DateTimeColumn get locallyUpdatedAt => dateTime().withDefault(currentDateAndTime)();
}